## https://dev.to/jameswallis/using-github-composite-actions-to-make-your-workflows-smaller-and-more-reusable-476l
name: 'Checkout and install'

inputs:
  cache_key:
    required: true
    type: string
  cache_path:
    required: true
    type: string
  npm_token:
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - run: |
        git fetch --no-tags --prune --depth=2 origin +refs/heads/master:refs/remotes/origin/master
      shell: bash
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Restore dependency cache
      uses: actions/cache@v2
      with:
        path: ${{ inputs.cache_path }}
        key: ${{ inputs.cache_key }}
    - name: Set up pnpm
      uses: pnpm/action-setup@v2.1.0
      with:
        version: 6
    - name: Install dependencies
      run: |
        pnpm install --frozen-lockfile
      shell: bash
